import "@/app/globals.css"
import { Metadata } from "next"
import { Inter } from "next/font/google"
import { fontSans } from "@/lib/fonts"
import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/providers/ThemeProvider"
import TanstackProvider from "@/providers/TanstackProvider";
import { TailwindIndicator } from "@/components/TailwindIndicator"


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable
          )}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="relative flex min-h-screen flex-col">
              {/* <Navbar /> */}
              <main className="flex-1">
                <TanstackProvider>{children}</TanstackProvider>
              </main>
              {/* <SiteFooter /> */}
            </div>
            <TailwindIndicator />
          </ThemeProvider>

        </body>
      </html>
    </>
  )
}
